name: Run Script

on: [push, pull_request]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jannekem/run-python-script-action@v1
      - uses: actions/setup-python@v3
        with:
          python-version: "3.8"
          script: |
            import os
            print("Directory contents:")
            for f in os.listdir():
                print(f)
      - name: Code check
        run: |
            pip install -e .
            python3 $(git ls-files '*.py')
